### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nicolasStevenin** [go-playground/ansi#1]
Hello,

Could you create a separate license file please ?
Thank you

**Comment by deankarn** [comment]
Thanks, didn’t realize I had missed adding one; I’ll add later this morning :smile:

P.S. it will be MIT licensed

**Comment by deankarn** [comment]
license added @nicolasStevenin

**Comment by nicolasStevenin** [comment]
Thanks a lot @joeybloggs  :)
